### ISSUE TITLE
Insertion de métadonnées: seule la première est remplacée

### ISSUE THREAD

**Issue by didierherisson** [Domlol/texomaker#2]
J'introduit mes exercices par un:
\exo[%@Difficulté@ ]{%@Titre@ }
Ça fonctionnait sur la version 2, plus sur la version 3 de texomaker: la première métadonnée que j'indique est bien remplacée sur cette ligne est bien remplacée, pas la seconde.

Typiquement, j'obtiens donc dans le fichier source de la feuille d'exo générée:
\exo[1 ]{%@Titre@ }
alors que j'attends:
\exo[1 ]{Le titre de mon exercice facile}
ce qui bien évidemment fait planter la compilation.

Si je mets dans texomaker \exo[1 ]{%@Titre@ }, cette fois-ci la balise de titre est correctement remplacée: la première rencontrée est traitée comme attendu, pas la seconde...

**Comment by Skade86** [comment]
Aïe. J'essaye de regarder ça très vite.

**Comment by Skade86** [comment]
Je viens de faire une correction qui devrait corriger le problème si je l'ai bien identifié. Je veux bien que tu essayes si cela fonctionne sur ton exemple (il faut compiler les sources récupérées directement dans le dépôt et pas les releases que je n'ai pas encore mises à jour).

**Comment by didierherisson** [comment]
Suite à mon incompétence à bien utiliser SVN du premier coup, j'ai commencé par vérifier qu'en recompilant l'ancienne version avec les mise à jour du système faites depuis, ça ne fonctionnait toujours pas, avant de passer à la dernière version, qui, elle, corrige le bug.

Merci!
