### ISSUE TITLE
installation sous windows?

### ISSUE THREAD

**Issue by ghost** [Domlol/texomaker#5]
Bonjour,
je cherche à me faire une base de données d'exercices de physique, et je suis donc tombée sur votre logiciel qui a l'air super. Sauf que je n'arrive pas à l'installer sur mon ordinateur avec windows.
j'ai bien récupéré les fichiers, mais je ne sais pas quoi en faire lol
Merci par avance pour votre aide!
Céline

**Comment by Skade86** [comment]
En fait pour Windows, il faut télécharger l'installateur sur la pages des Releases, à savoir ce lien : 

https://github.com/Domlol/texomaker/releases/download/v3.0.1/texomaker-3.0.1-win-setup.exe

Pour avoir de l'aide, vous pouvez en revanche récupérer le contenu du répertoire "docs" sur la liste des fichiers que vous avez récupéré.

N'hésitez pas à me recontacter si vous rencontrez des problèmes.

**Comment by ghost** [comment]
Merci beaucoup!
j'ai essayé de l'installer. malheureusement, j'ai un souci windows
indépendant de votre programme. Voici l'erreur:
This application failed to start because it could not find or load the Qt
platform plugin "windows".
et j'arrive pas pas à m'en dépatouiller.
Merci quand même!
Céline

**Comment by Skade86** [comment]
Cela ne venait pas de votre machine, mais d'un problème avec la version pour Windows (il manquait une bibliothèque).
Je viens de publier une mise à jour pour Windows (version 3.0.2) qui corrige le problème.

**Comment by ghost** [comment]
c'est ok pour moi ici! c'est vraiment un super outil. Merci beaucoup
d'avoir créé et partagé ça.
